"""Writes THIRD_PARTY_NOTICES.md from what the installers actually contain.

Run after `npm run bundle:python -- arm64` and `-- x64` (it reads src-tauri/python-*/), with cargo on PATH:
    .venv\\Scripts\\python.exe scripts\\third-party-notices.py
"""
import email
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TAURI = ROOT / "src-tauri"
TARGETS = {"arm64": "aarch64-pc-windows-msvc", "x64": "x86_64-pc-windows-msvc"}
LICENSE_FILE = re.compile(r"^(licen[cs]e|copying|notice|unlicense)", re.I)

HEADER = """# Third-party notices

소리글 is MIT licensed (see `LICENSE`). The installers also contain, or download on first run, the third-party
components below. Generated by `scripts/third-party-notices.py`; do not edit by hand.

## Downloaded on first run (not included in the installers)

| Component | Source | License |
|---|---|---|
| Whisper large-v3-turbo (weights, tokenizer, configs) | [openai/whisper-large-v3-turbo](https://huggingface.co/openai/whisper-large-v3-turbo) | MIT |
| Whisper large-v3-turbo, Snapdragon QNN export (ARM64 only) | [FluidInference/whisper-large-v3-turbo-qnn](https://huggingface.co/FluidInference/whisper-large-v3-turbo-qnn) | Apache-2.0 |
| Whisper large-v3-turbo, ONNX export | [onnx-community/whisper-large-v3-turbo](https://huggingface.co/onnx-community/whisper-large-v3-turbo) | MIT (from the original model) |
| WeSpeaker ResNet34-LM speaker embedding (VoxCeleb) | [k2-fsa/sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx/releases/tag/speaker-recongition-models), [wenet-e2e/wespeaker](https://github.com/wenet-e2e/wespeaker) | Apache-2.0 |
| FFmpeg 7.1 (gyan.dev "essentials" build, via the imageio-ffmpeg 0.6.0 wheel) | [PyPI imageio-ffmpeg](https://pypi.org/project/imageio-ffmpeg/), [gyan.dev](https://www.gyan.dev/ffmpeg/builds/), source: [ffmpeg.org](https://ffmpeg.org/download.html) | GPL-3.0-or-later (FFmpeg build); BSD-2-Clause (imageio-ffmpeg) |

The app runs FFmpeg as a separate program; it is downloaded from PyPI by the user's own first run and is not
distributed with 소리글.

## Included in the installers

| Component | License | Where the license text is |
|---|---|---|
| Python 3.12.10 (python.org embeddable package) | PSF-2.0 (and the licenses listed in its `LICENSE.txt`) | `python/LICENSE.txt` |
| Microsoft Visual C++ runtime (`msvcp140*.dll`, `vcruntime140*.dll`) | Microsoft Visual Studio redistributable terms | — |
| Qualcomm AI Engine Direct (QNN) libraries inside `onnxruntime-qnn` (ARM64 only) | Qualcomm AI Stack License (redistribution as part of an application, object code only) | `python/Lib/site-packages/onnxruntime/Qualcomm AI Hub Proprietary License.pdf`, `python/Lib/gpu-packages/onnxruntime_qnn/Qualcomm_LICENSE.pdf` |
| ONNX Runtime and its dependencies | MIT, see its notices | `python/Lib/*/onnxruntime/ThirdPartyNotices.txt` |
| OpenVINO runtime and its dependencies (x64 only) | Apache-2.0, see its third-party programs | `python/Lib/site-packages/openvino-*.dist-info/` |
| 에이투지체 (A2Z) font, © 2026 PT&, Lee Juim; Latin glyphs from Outfit | SIL Open Font License 1.1 | `frontend/A2Z/OFL.txt` in this repository, `A2Z/OFL.txt` in the app's assets |
| React, React DOM 18.3.1 | MIT | `vendor/LICENSE.react.txt`, `vendor/LICENSE.react-dom.txt` (app assets) |
| WebView2 | Microsoft; the installer downloads Microsoft's bootstrapper when WebView2 is missing | — |

"""


def python_packages():
    rows = {}
    for arch in TARGETS:
        for folder in ("site-packages", "gpu-packages"):
            lib = TAURI / f"python-{arch}" / "Lib" / folder
            for meta in sorted(lib.glob("*.dist-info/METADATA")):
                message = email.message_from_bytes(meta.read_bytes())
                license_name = message.get("License-Expression") or (message.get("License") or "").strip()
                if not license_name or len(license_name) > 60:
                    classifiers = [c.split("::")[-1].strip() for c in message.get_all("Classifier", []) if c.startswith("License ::")]
                    license_name = "; ".join(classifiers) or "see license file"
                key = (message["Name"], message["Version"])
                rows.setdefault(key, [license_name, []])[1].append(f"{arch} `{folder}`")
    lines = ["## Python packages (license files ship in `python/Lib/<folder>/<package>.dist-info/`)", "",
             "| Package | Version | License | Installer |", "|---|---|---|---|"]
    for (name, version), (license_name, where) in sorted(rows.items(), key=lambda item: item[0][0].lower()):
        lines.append(f"| {name} | {version} | {license_name} | {', '.join(where)} |")
    return lines + [""]


def rust_crates():
    metadata = json.loads(subprocess.run(["cargo", "metadata", "--format-version", "1", "--locked"], cwd=TAURI,
                                         capture_output=True, check=True).stdout)
    packages = {(p["name"], p["version"]): p for p in metadata["packages"]}
    used = set()
    for triple in TARGETS.values():
        tree = subprocess.run(["cargo", "tree", "--locked", "--target", triple, "-e", "normal", "--prefix", "none",
                               "-f", "{p}"], cwd=TAURI, capture_output=True, text=True, check=True).stdout
        for line in tree.splitlines():
            match = re.match(r"(\S+) v(\S+)", line)
            if match and (match[1], match[2]) in packages and packages[(match[1], match[2])]["source"]:
                used.add((match[1], match[2]))
    table = ["## Rust crates compiled into `sori-gul.exe`", "", "| Crate | Version | License |", "|---|---|---|"]
    texts, without_file = {}, []
    for key in sorted(used):
        package = packages[key]
        table.append(f"| {key[0]} | {key[1]} | {package.get('license') or 'see text below'} |")
        folder = Path(package["manifest_path"]).parent
        files = sorted(p for p in folder.iterdir() if p.is_file() and LICENSE_FILE.match(p.name))
        for file in files:
            body = file.read_text(encoding="utf-8", errors="replace").strip()
            texts.setdefault(hashlib.sha256(body.encode()).hexdigest(), [body, []])[1].append(f"{key[0]} {key[1]}")
        if not files:
            without_file.append(package)
    lines = table + ["", "### Rust crate license texts", "",
                     "Each text below is reproduced once, followed by the crates that ship it.", ""]
    for body, crates in sorted(texts.values(), key=lambda item: item[1][0]):
        lines += [f"<details><summary>{', '.join(crates)}</summary>", "", "```text", body, "```", "", "</details>", ""]
    # Some crates publish no license file; point to a block above that carries the standard text of their license.
    canonical = {"MIT": "Permission is hereby granted, free of charge", "Apache-2.0": "Apache License",
                 "BSD-3-Clause": "Neither the name", "MPL-2.0": "Mozilla Public License Version 2.0"}
    example = {spdx: next((crates[0] for body, crates in texts.values() if phrase in body), "?")
               for spdx, phrase in canonical.items()}
    lines += ["### Crates that publish no license file", "",
              "| Crate | Version | License | Authors | Repository | Standard text above in the block of |",
              "|---|---|---|---|---|---|"]
    for package in without_file:
        spdx = [name for name in canonical if name in (package.get("license") or "")]
        lines.append(f"| {package['name']} | {package['version']} | {package.get('license')} | "
                     f"{', '.join(package.get('authors') or []) or '—'} | {package.get('repository') or '—'} | "
                     f"{'; '.join(f'{name}: {example[name]}' for name in spdx)} |")
    return lines + [""]


def main():
    out = [HEADER] + python_packages() + rust_crates()
    (ROOT / "THIRD_PARTY_NOTICES.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote THIRD_PARTY_NOTICES.md")


if __name__ == "__main__":
    main()
